name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CMAKE_ROOT: /$GITHUB_WORKSPACE/Projects/CMake/build
  CMAKE_BUILD_PATH: $CMAKE_ROOT/build

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1

    - name: Create Build Environment
      shell: bash
      run: |
        cmake -E make_directory $CMAKE_BUILD_PATH
        ls $CMAKE_ROOT

    - name: Configure CMake
      shell: bash
      run: cmake -S $CMAKE_ROOT -B $CMAKE_BUILD_PATH -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      shell: bash
      run: cmake --build $CMAKE_BUILD_PATH --config $BUILD_TYPE
