name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    
    - name: Pull submodules
      run: git submodule update --init

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/Projects/CMake/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/Projects/CMake/build
      run: cmake $GITHUB_WORKSPACE/Projects/CMake -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{runner.workspace}}/Projects/CMake/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

